---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: latency-worker
  namespace: XXX_NAMESPACE_XXX
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 2
  minReadySeconds: 15
  template:
    metadata:
      labels:
        app: worker
        revision: "XXX_CHANGED_XXX"
    spec:
      restartPolicy: Always
      containers:
      - name: latency-worker
        image: XXX_IMAGE_REGISTRY_XXXredis-latency-tester:latest
        imagePullPolicy: XXX_IMAGE_PULL_POLICY_XXX
        env:
          - name: changed
            value: "XXX_CHANGED_XXX"
