---
apiVersion: kubedb.com/v1alpha1
kind: Redis
metadata:
  name: redis
  namespace: XXX_NAMESPACE_XXX
spec:
  version: 5.0.3-v1	
  mode: Cluster
  cluster:
    master: 3
    replicas: 1
  storageType: Durable
  storage:
    storageClassName: standard
    resources:
      requests:
        storage: 1Gi
    accessModes:
    - ReadWriteOnce
  terminationPolicy: Wipeout
  updateStrategy:
    type: RollingUpdate
  podTemplate:
    spec:
      resources:
        requests:
          memory: 1Gi
          cpu: 1.1
